<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <!--Consider an application in which the results of football games are to be represented in XML.
        (The description below is deliberately more open-ended than the one above.)
        For each game, we want to be
        able to represent the two teams involved, which one was playing at home, which players scored goals (some
        of which may have been penalties) and the time when each was scored, and which players were shown yellow or
        red cards. You might use some attributes this time, for practice. See the English Premiership results for
        some sample data (click on the > icon to the left of a result to see the details about goals and cards).
        -->
<!DOCTYPE Results [
        <!ELEMENT Results (Result*)>
        <!ELEMENT Result (home, away?, result?, goals*)>
        <!ELEMENT home (#PCDATA)>
        <!ELEMENT away (#PCDATA)>
        <!ELEMENT result (#PCDATA)>
        <!ELEMENT goals (goal*)>
        <!ELEMENT goal (scorer*)>
        <!ELEMENT scorer (#PCDATA)>
        <!ATTLIST scorer type (penalty|game) #REQUIRED>
        ]>
<Results>
    <Result>
        <home>Everton</home>
        <away>Liverpool</away>
        <result>1-0</result>
        <goals>
            <goal>
                <scorer type="penalty">Bill Billson</scorer>
            </goal>
        </goals>
    </Result>
    <Result>
        <home>Luton</home>
        <away>Chelsea</away>
        <result>2-0</result>
        <goals>
            <goal>
                <scorer type="penalty">Bill Billson</scorer>
            </goal>
            <goal>
                <scorer type="game">Bill Billson</scorer>
            </goal>
        </goals>
    </Result>
    <Result>
        <home>Chelsea</home>
        <away>Fulham</away>
        <result>1-1</result>
        <goals>
            <goal>
                <scorer type="game">Bill Billson</scorer>
            </goal>
            <goal>
                <scorer type="penalty">Bill Billson</scorer>
            </goal>
        </goals>
    </Result>
</Results>