=== tristian2/IWTRevision/xsl/diary/diary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT diary       (event*) >
<!ELEMENT event       (date, (time, duration)?, description, repeat?) >
<!ELEMENT repeat      (until | occurrences)? >
<!ELEMENT date        (#PCDATA) >
<!ELEMENT time        (#PCDATA) >
<!ELEMENT duration    (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT until       (#PCDATA) >
<!ELEMENT occurrences (#PCDATA) >
<!ATTLIST repeat
        frequency (weekly | monthly | yearly) "weekly" >

=== tristian2/IWTRevision/xsl/diary/diary.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="diary.xsl" type="text/xsl"?>
<!DOCTYPE diary SYSTEM "diary.dtd">
<diary>
    <event>
        <date>2/10/2002</date>
        <time>18:00</time>
        <duration>3:00</duration>
        <description>MScEC lecture</description>
        <repeat>
            <until>11/12/2002</until>
        </repeat>
    </event>
    <event>
        <date>27/06/2002</date>
        <description>An important birthday</description>
        <repeat frequency="yearly"/>
    </event>
    <event>
        <date>13/08/2014</date>
        <description>TRIS THE KING'S birthday</description>
        <repeat frequency="yearly"/>
    </event>
</diary>
